#!/usr/bin/env Rscript
# scripts/11_table1.R
#
# Survey-weighted Table 1 of baseline characteristics, overall and stratified by
# all-cause mortality status within the follow-up cap. Continuous variables are
# reported as survey-weighted mean (SD); categorical variables as weighted
# percentage. Emits a LaTeX fragment for the manuscript and a plain CSV.
#
# Inputs:  data/processed/cohort_with_scores.rds
# Outputs: manuscript/table1_baseline.tex, results/table1_baseline.csv

.libPaths("/home/po/projects/work/longitudinal-mets-validation/renv/library/R-4.3/x86_64-pc-linux-gnu")

suppressMessages({
  library(survey)
  library(dplyr)
})

source("R/utils/survey_design.R")

df  <- readRDS("data/processed/cohort_with_scores.rds")
des <- build_survey_design(df)

des_alive <- subset(des, event_allcause == 0)
des_dead  <- subset(des, event_allcause == 1)
designs   <- list(Overall = des, Alive = des_alive, Death = des_dead)
n_unwt    <- c(Overall = nrow(df),
               Alive   = sum(df$event_allcause == 0),
               Death   = sum(df$event_allcause == 1))

continuous <- list(
  age            = "Age, years",
  bmi            = "Body mass index, kg/m$^2$",
  waist_cm       = "Waist circumference, cm",
  sbp            = "Systolic blood pressure, mmHg",
  dbp            = "Diastolic blood pressure, mmHg",
  fasting_glucose= "Fasting glucose, mg/dL",
  hdl            = "HDL cholesterol, mg/dL",
  triglycerides  = "Triglycerides, mg/dL",
  total_chol     = "Total cholesterol, mg/dL"
)

# Categorical variables expressed as the weighted percentage of a reference level.
categorical <- list(
  list(var = "sex",                level = "female",       label = "Female sex"),
  list(var = "race",               level = "NHWhite",      label = "Non-Hispanic White"),
  list(var = "race",               level = "NHBlack",      label = "Non-Hispanic Black"),
  list(var = "race",               level = "MexicanAm",    label = "Mexican American"),
  list(var = "race",               level = "NHAsian",      label = "Non-Hispanic Asian"),
  list(var = "current_smoker",     level = TRUE,           label = "Current smoker"),
  list(var = "bp_treatment",       level = TRUE,           label = "Antihypertensive treatment"),
  list(var = "physical_active",    level = TRUE,           label = "Physically active"),
  list(var = "family_history_dm",  level = "first_degree", label = "Family history of diabetes"),
  list(var = "prior_high_glucose", level = TRUE,           label = "Prior high glucose / prediabetes")
)

fmt_cont <- function(design, v) {
  m  <- svymean(as.formula(paste0("~", v)), design, na.rm = TRUE)
  sdv <- sqrt(coef(svyvar(as.formula(paste0("~", v)), design, na.rm = TRUE)))
  sprintf("%.1f (%.1f)", coef(m)[1], sdv[1])
}

fmt_cat <- function(design, v, level) {
  form <- as.formula(paste0("~factor(", v, ")"))
  m <- svymean(form, design, na.rm = TRUE)
  nm <- paste0("factor(", v, ")", level)
  if (!nm %in% names(coef(m))) return("--")
  sprintf("%.1f", 100 * coef(m)[nm])
}

rows <- list()
for (v in names(continuous)) {
  vals <- sapply(designs, fmt_cont, v = v)
  rows[[length(rows) + 1]] <- c(label = continuous[[v]], vals)
}
for (cat_spec in categorical) {
  vals <- sapply(designs, fmt_cat, v = cat_spec$var, level = cat_spec$level)
  rows[[length(rows) + 1]] <- c(label = cat_spec$label, vals)
}

tab <- do.call(rbind, lapply(rows, function(r)
  data.frame(Characteristic = r["label"], Overall = r["Overall"],
             Alive = r["Alive"], Death = r["Death"],
             stringsAsFactors = FALSE, row.names = NULL)))

write.csv(tab, "results/table1_baseline.csv", row.names = FALSE)

# LaTeX fragment ------------------------------------------------------------
con <- file("manuscript/table1_baseline.tex", "w")
wl  <- function(...) writeLines(paste0(...), con)

wl("% Auto-generated by scripts/11_table1.R. Do not edit by hand.")
wl("\\begin{table}[h]")
wl("\\centering")
wl("\\caption{Survey-weighted baseline characteristics of the pooled NHANES 1999--2018 fasting subsample (N = ",
   format(n_unwt["Overall"], big.mark = "{,}"),
   "), overall and stratified by all-cause mortality status within the 10-year follow-up cap. ",
   "Continuous variables are reported as survey-weighted mean (standard deviation); ",
   "categorical variables as weighted percentage. Counts are unweighted.}")
wl("\\label{tab:baseline}")
wl("\\begin{tabular}{lccc}")
wl("\\toprule")
wl(sprintf("Characteristic & Overall & Alive & Death \\\\"))
wl(sprintf("& (n = %s) & (n = %s) & (n = %s) \\\\",
           format(n_unwt["Overall"], big.mark = "{,}"),
           format(n_unwt["Alive"],   big.mark = "{,}"),
           format(n_unwt["Death"],   big.mark = "{,}")))
wl("\\midrule")
for (i in seq_len(nrow(tab))) {
  wl(sprintf("%s & %s & %s & %s \\\\",
             tab$Characteristic[i], tab$Overall[i], tab$Alive[i], tab$Death[i]))
}
wl("\\bottomrule")
wl("\\end{tabular}")
wl("\\end{table}")
close(con)

message("\n=== Table 1 ===")
print(tab, row.names = FALSE)
message("\nWrote manuscript/table1_baseline.tex and results/table1_baseline.csv")
